In [1]:
# Good

In [1]:
import tensorflow as tf

2023-07-26 18:35:57.246699: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-26 18:35:58.189748: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
print(tf.config.list_physical_devices('GPU'))
print("TensorFlow version:", tf.__version__)


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
TensorFlow version: 2.12.1


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 2s 0us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2023-07-26 18:36:52.518722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 29924 MB memory:  -> device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0


In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.09998153,  0.6579353 , -0.12321663, -0.3284828 ,  0.00622772,
        -0.08460405, -0.33907774, -0.12064759, -0.04216651, -0.41262075]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.0944104 , 0.20145541, 0.09224205, 0.07512474, 0.10498951,
        0.09587341, 0.074333  , 0.09247933, 0.10002961, 0.06906251]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [9]:
loss_fn(y_train[:1], predictions).numpy()


2.3447266

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5


2023-07-26 18:38:30.919485: I tensorflow/compiler/xla/service/service.cc:169] XLA service 0x7ff61001a5a0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-07-26 18:38:30.919591: I tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): Tesla V100-PCIE-32GB, Compute Capability 7.0
2023-07-26 18:38:30.934379: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2023-07-26 18:38:31.175861: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:424] Loaded cuDNN version 8600
2023-07-26 18:38:31.789578: I ./tensorflow/compiler/jit/device_compiler.h:180] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1875/1875 [==============================] - 11s 5ms/step - loss: 0.2983 - accuracy: 0.9126
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1441 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1067 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0858 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0749 - accuracy: 0.9766


In [12]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 1s - loss: 0.0725 - accuracy: 0.9777 - 849ms/epoch - 3ms/step


[0.07247443497180939, 0.9776999950408936]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.4240113e-08, 2.8213416e-09, 2.3678615e-07, 5.2153478e-05,
        1.2778319e-13, 9.3803550e-08, 8.8133499e-13, 9.9994361e-01,
        2.9629970e-08, 3.7805262e-06],
       [6.6913208e-07, 2.1920734e-04, 9.9970704e-01, 7.1660645e-05,
        2.1650625e-17, 2.2640018e-07, 1.0538164e-08, 1.3030635e-11,
        1.2231657e-06, 1.6859050e-13],
       [2.8101380e-07, 9.9496174e-01, 3.0519956e-04, 2.9661420e-05,
        1.3671241e-04, 6.0440201e-05, 2.5950867e-05, 3.3378156e-03,
        1.1395847e-03, 2.7408100e-06],
       [9.9997735e-01, 2.7674571e-12, 1.3317525e-05, 1.5206270e-08,
        4.5106191e-10, 5.2040093e-08, 5.0784238e-06, 2.1744638e-06,
        2.1970425e-10, 1.9948179e-06],
       [1.1689706e-07, 1.6035645e-10, 5.8976852e-06, 1.7821742e-08,
        9.9667835e-01, 5.6014169e-08, 1.0178936e-06, 2.3317105e-05,
        1.0062815e-06, 3.2902916e-03]], dtype=float32)>